sonar.projectKey=fitforge-frontend
sonar.projectName=fitforge-frontend
sonar.sources=src
sonar.exclusions=**/target/**, **/build/**, **/dist/**, **/node_modules/**, **/html/**

sonar.sourceEncoding=UTF-8
